# Generated by Django 5.0.4 on 2024-04-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('cost_center', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('person_in_charge', models.CharField(max_length=128)),
            ],
        ),
    ]
