# Generated by Django 4.2.11 on 2024-05-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_remove_companypayrollsettings_active'),
        ('employee_management', '0002_alter_location_city_alter_location_cost_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40, verbose_name='Surname or Last Name')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('other_names', models.CharField(blank=True, default='', max_length=100, verbose_name='Other names')),
                ('maiden_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Maiden name')),
                ('nic', models.CharField(max_length=20, verbose_name='National Identity Card Number or Social Security Number')),
                ('gender', models.CharField(max_length=5, verbose_name='Gender')),
                ('employee_code', models.CharField(max_length=6, unique=True, verbose_name='Employee Code')),
                ('badge_access_control_number', models.CharField(blank=True, default='', max_length=25, unique=True, verbose_name='Badge Access Control Number')),
                ('mobile_number', models.CharField(blank=True, default='', max_length=15, verbose_name='Mobile Number')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='Phone Number')),
                ('postcode', models.IntegerField(blank=True, null=True, verbose_name='Post Code')),
                ('date_joined', models.DateField(verbose_name='Joining Date')),
                ('in_current_position_since', models.DateField(verbose_name='In current position since')),
                ('post', models.CharField(max_length=10, verbose_name='Post')),
                ('employment_type', models.CharField(max_length=15, verbose_name='Employment Type')),
                ('office_site', models.CharField(blank=True, default='', max_length=20, verbose_name='Office Site')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('reason_of_departure', models.CharField(blank=True, default='', max_length=255, verbose_name='Reason of Departure')),
                ('suspension_date', models.DateField(verbose_name='Suspension Date')),
                ('reason_for_suspension', models.CharField(blank=True, default='', max_length=255, verbose_name='Reason for Suspension')),
                ('normal_working_monday', models.BooleanField(default=True, verbose_name='Monday')),
                ('normal_working_tuesday', models.BooleanField(default=True, verbose_name='Tuesday')),
                ('normal_working_wednesday', models.BooleanField(default=True, verbose_name='Wednesday')),
                ('normal_working_thursday', models.BooleanField(default=True, verbose_name='Thursday')),
                ('normal_working_friday', models.BooleanField(default=True, verbose_name='Friday')),
                ('normal_working_saturday', models.BooleanField(default=True, verbose_name='Saturday')),
                ('normal_working_sunday', models.BooleanField(default=True, verbose_name='Sunday')),
                ('active_employee', models.BooleanField(default=False, verbose_name='Active Employee')),
                ('salary_payment_interval', models.CharField(max_length=30, verbose_name='Salary Payment')),
                ('paye_income_tax_enabled', models.BooleanField(default=True, verbose_name='')),
                ('tan', models.CharField(max_length=32)),
                ('pension_fund_number', models.CharField(max_length=32)),
                ('npf_nsf_contribution_enabled', models.BooleanField(default=True)),
                ('contribution_code', models.CharField(max_length=32)),
                ('paid_by_bank_transfer', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.workingcalendar', verbose_name='Calendar')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.department', verbose_name='Department')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management.employeefile', verbose_name='First Version of this Employee Record')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEDFDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edf_income_threshold', models.CharField(max_length=30)),
                ('deductions_child_pursuing_undergraduate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deductions_secured_housing_loan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deductions_medical_health', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deductions_solar_energy_investment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deductions_household_employees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deductions_rainwater_harvesting', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount_exemption', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paye_paid_in_previous_employment', models.BooleanField(default=True)),
                ('employeeFile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employeefile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=128, verbose_name='Bank Account Number')),
                ('currency', models.CharField(max_length=32, verbose_name='Currency')),
                ('split_type', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Split Type')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount Destined')),
                ('employeeFile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employeefile')),
            ],
        ),
    ]
