# Generated by Django 4.2.11 on 2024-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_employeefile_employeeedfdetails_employeebank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='pension_fund_number',
            field=models.CharField(max_length=32, verbose_name='Pension Fund Number'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='tan',
            field=models.CharField(max_length=32, verbose_name='Tax Acc/Identification Number'),
        ),
    ]
