# Generated by Django 4.2.11 on 2024-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_rename_normal_working_friday_employeefile_friday_working_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='departure_date',
            field=models.DateField(null=True, verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='suspension_date',
            field=models.DateField(null=True, verbose_name='Suspension Date'),
        ),
    ]
