# Generated by Django 4.2.11 on 2024-05-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0008_alter_employeefile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='contribution_code',
            field=models.CharField(choices=[('S', 'Standard'), ('D', 'Self Employed/Non Employed/Prescribed'), ('G', 'Government Share'), ('N', 'Only NSF (Employer Share only)'), ('V', 'No Contributions'), ('X', 'Exempted')], default='S', help_text='Select the type of contribution code.', max_length=1),
        ),
    ]
