# Generated by Django 4.2.11 on 2024-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0009_alter_employeefile_contribution_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='suspension_date',
            field=models.DateField(blank=True, null=True, verbose_name='Suspension Date'),
        ),
    ]
