# Generated by Django 4.2.11 on 2024-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0012_alter_employeefile_badge_access_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
