# Generated by Django 4.2.11 on 2024-05-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_alter_companybankaccount_bank_name_and_more'),
        ('employee_management', '0013_employeefile_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='active_employee',
            field=models.BooleanField(blank=True, default=False, verbose_name='Active Employee'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.workingcalendar', verbose_name='Calendar'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='date_joined',
            field=models.DateField(blank=True, default='', verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='employee_code',
            field=models.CharField(blank=True, default='', max_length=6, unique=True, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='friday_overtime',
            field=models.BooleanField(blank=True, default=True, verbose_name='Overtime permitted on Friday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='friday_working',
            field=models.BooleanField(blank=True, default=True, verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='in_current_position_since',
            field=models.DateField(blank=True, default='', verbose_name='In current position since'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='monday_overtime',
            field=models.BooleanField(blank=True, default=True, verbose_name='Overtime permitted on Monday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='monday_working',
            field=models.BooleanField(blank=True, default=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='nic',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='National Identity Card Number or Social Security Number'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='npf_nsf_contribution_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='paid_by_bank_transfer',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='paye_income_tax_enabled',
            field=models.BooleanField(blank=True, default=True, verbose_name='Contributes PAYE'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='pension_fund_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Pension Fund Number'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='post',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='salary_payment_interval',
            field=models.CharField(blank=True, max_length=30, verbose_name='Salary Payment'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='saturday_overtime',
            field=models.BooleanField(blank=True, default=False, verbose_name='Overtime permitted on Saturday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='saturday_working',
            field=models.BooleanField(blank=True, default=False, verbose_name='Saturday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='sunday_overtime',
            field=models.BooleanField(blank=True, default=False, verbose_name='Overtime permitted on Sunday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='sunday_working',
            field=models.BooleanField(blank=True, default=False, verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='tan',
            field=models.CharField(blank=True, max_length=32, verbose_name='Tax Acc/Identification Number'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='thursday_overtime',
            field=models.BooleanField(blank=True, default=True, verbose_name='Overtime permitted on Thursday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='thursday_working',
            field=models.BooleanField(blank=True, default=True, verbose_name='Thursday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='tuesday_overtime',
            field=models.BooleanField(blank=True, default=True, verbose_name='Overtime permitted on Tuesday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='tuesday_working',
            field=models.BooleanField(blank=True, default=True, verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='wednesday_overtime',
            field=models.BooleanField(blank=True, default=True, verbose_name='Overtime permitted on Wednesday'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='wednesday_working',
            field=models.BooleanField(blank=True, default=True, verbose_name='Wednesday'),
        ),
    ]
