# Generated by Django 4.2.11 on 2024-05-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0014_alter_employeefile_active_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='in_current_position_since',
            field=models.DateField(blank=True, null=True, verbose_name='In current position since'),
        ),
    ]
