# Generated by Django 4.2.11 on 2024-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0015_alter_employeefile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='employee_code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Employee Code'),
        ),
    ]
