# Generated by Django 4.2.11 on 2024-05-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0016_alter_employeefile_employee_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeefile',
            unique_together=set(),
        ),
    ]
