# Generated by Django 4.2.11 on 2024-05-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0017_alter_employeefile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='employment_type',
            field=models.CharField(choices=[('FULL', 'Full-Time'), ('PART', 'Part-Time'), ('CONT', 'Contract'), ('TEMP', 'Temporary'), ('INTERN', 'Internship'), ('FREE', 'Freelance')], default='FULL', help_text='Defines the type of employment contract.', max_length=6, verbose_name='Employment Type'),
        ),
    ]
