# Generated by Django 4.2.11 on 2024-05-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0018_employeefile_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebank',
            name='employeeFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employeefile'),
        ),
    ]
