# Generated by Django 4.2.11 on 2024-05-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0019_alter_employeebank_employeefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_code', models.CharField(max_length=25)),
                ('amount', models.IntegerField(verbose_name='Allowed')),
                ('rollover', models.IntegerField(verbose_name='Rollover')),
                ('taken', models.IntegerField(verbose_name='Taken')),
                ('available', models.IntegerField(verbose_name='Available')),
                ('employeeFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employeefile')),
            ],
        ),
    ]
