# Generated by Django 4.2.11 on 2024-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0020_employeeleavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Allowed'),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='available',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='rollover',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Rollover'),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='taken',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Taken'),
        ),
    ]
