# Generated by Django 4.2.11 on 2024-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0023_alter_employeefile_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='active_employee',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active Employee'),
        ),
    ]
