# Generated by Django 4.2.11 on 2024-05-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0024_alter_employeefile_active_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_loan_code', models.CharField(max_length=15)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('loan_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('paid_month', models.DateField(verbose_name='Paid Month')),
                ('repayment_monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('repayment_start_month', models.DateField(verbose_name='Repayment Start Month')),
                ('loan_amount_manually_cleared', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('employeeFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employeefile')),
            ],
        ),
    ]
