# Generated by Django 4.2.11 on 2024-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0025_employeeloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloan',
            name='paid_month',
            field=models.DateField(blank=True, null=True, verbose_name='Paid Month'),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='repayment_start_month',
            field=models.DateField(blank=True, null=True, verbose_name='Repayment Start Month'),
        ),
    ]
