# Generated by Django 4.2.11 on 2024-06-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_alter_companybankaccount_bank_name_and_more'),
        ('employee_management', '0026_alter_employeeloan_paid_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employeefile')),
                ('payrollGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.payrollgroup')),
            ],
        ),
    ]
