# Generated by Django 4.2.11 on 2024-04-18 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('monday_working', models.BooleanField(default=True)),
                ('monday_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('monday_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('monday_overtime', models.BooleanField(default=True)),
                ('tuesday_working', models.BooleanField(default=True)),
                ('tuesday_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('tuesday_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_overtime', models.BooleanField(default=True)),
                ('wed_working', models.BooleanField(default=True)),
                ('wed_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('wed_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('wed_overtime', models.BooleanField(default=True)),
                ('thurs_working', models.BooleanField(default=True)),
                ('thurs_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('thurs_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('thurs_overtime', models.BooleanField(default=True)),
                ('fri_working', models.BooleanField(default=True)),
                ('fri_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('fri_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('fri_overtime', models.BooleanField(default=True)),
                ('sat_working', models.BooleanField(default=False)),
                ('sat_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('sat_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('sat_overtime', models.BooleanField(default=False)),
                ('sun_working', models.BooleanField(default=False)),
                ('sun_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('sun_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('sun_overtime', models.BooleanField(default=False)),
                ('lateness_minimum_minutes', models.PositiveSmallIntegerField(default=5)),
                ('overtime_minimum_minutes', models.PositiveSmallIntegerField(default=30)),
                ('overtime_deduct_lateness', models.BooleanField(default=False)),
                ('overtime_minimum_arrival_minutes', models.PositiveSmallIntegerField(default=0)),
                ('overtime_after_hours_break', models.PositiveSmallIntegerField(default=0)),
                ('overtime_after_mins', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('parent_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.department')),
            ],
        ),
    ]
