# Generated by Django 4.2.11 on 2024-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_workingcalendar_fri_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingcalendar',
            name='fri_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Friday End Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='fri_overtime',
            field=models.BooleanField(default=True, verbose_name='Overtime permitted on Friday'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='fri_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Friday Start Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='fri_working',
            field=models.BooleanField(default=True, verbose_name='Friday Working'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='lateness_minimum_minutes',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Minimum lateness for Deduction eligibility'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='monday_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday End Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='monday_overtime',
            field=models.BooleanField(default=True, verbose_name='Overtime permitted on Monday'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='monday_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday Start Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='monday_working',
            field=models.BooleanField(default=True, verbose_name='Monday Working'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='overtime_after_hours_break',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Duration to remove from overtime hours for break'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='overtime_after_mins',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='After how much time in minutes, does the overtime'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='overtime_deduct_lateness',
            field=models.BooleanField(default=False, verbose_name='Deduct lateness from overtime?'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='overtime_minimum_arrival_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Minimum duration to arrive before working hours to count as overtime '),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='overtime_minimum_minutes',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Minimum overtime minutes for payment'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='sat_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Saturday End Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='sat_overtime',
            field=models.BooleanField(default=False, verbose_name='Overtime permitted on Saturday'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='sat_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Saturday Start Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='sat_working',
            field=models.BooleanField(default=False, verbose_name='Saturday Working'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='sun_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Sunday End Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='sun_overtime',
            field=models.BooleanField(default=False, verbose_name='Overtime permitted on Sunday'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='sun_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Sunday Start Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='sun_working',
            field=models.BooleanField(default=False, verbose_name='Sunday Working'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='thurs_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Thursday End Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='thurs_overtime',
            field=models.BooleanField(default=True, verbose_name='Overtime permitted on Thursday'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='thurs_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Thursday Start Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='thurs_working',
            field=models.BooleanField(default=True, verbose_name='Thursday Working'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='tuesday_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tuesday End Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='tuesday_overtime',
            field=models.BooleanField(default=True, verbose_name='Overtime permitted on Tuesday'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='tuesday_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tuesday Start Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='tuesday_working',
            field=models.BooleanField(default=True, verbose_name='Tuesday Working'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='wed_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Wednesday End Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='wed_overtime',
            field=models.BooleanField(default=True, verbose_name='Overtime permitted on Wednesday'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='wed_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Wednesday Start Time'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='wed_working',
            field=models.BooleanField(default=True, verbose_name='Wednesday Working'),
        ),
    ]
