# Generated by Django 4.2.11 on 2024-04-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_department_parent_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='fri_end_time',
            new_name='friday_end_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='fri_overtime',
            new_name='friday_overtime',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='fri_start_time',
            new_name='friday_start_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='fri_working',
            new_name='friday_working',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='sat_end_time',
            new_name='saturday_end_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='sat_overtime',
            new_name='saturday_overtime',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='sat_start_time',
            new_name='saturday_start_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='sat_working',
            new_name='saturday_working',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='sun_end_time',
            new_name='sunday_end_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='sun_overtime',
            new_name='sunday_overtime',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='sun_start_time',
            new_name='sunday_start_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='sun_working',
            new_name='sunday_working',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='thurs_end_time',
            new_name='thursday_end_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='thurs_overtime',
            new_name='thursday_overtime',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='thurs_start_time',
            new_name='thursday_start_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='thurs_working',
            new_name='thursday_working',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='wed_end_time',
            new_name='wednesday_end_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='wed_overtime',
            new_name='wednesday_overtime',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='wed_start_time',
            new_name='wednesday_start_time',
        ),
        migrations.RenameField(
            model_name='workingcalendar',
            old_name='wed_working',
            new_name='wednesday_working',
        ),
    ]
