# Generated by Django 4.2.11 on 2024-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_fri_end_time_workingcalendar_friday_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=128)),
                ('branch', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=128)),
                ('iban', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=32)),
                ('default_bank', models.BooleanField(default=False, verbose_name='Default Bank?')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=128)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_range', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('primary', models.BooleanField(default=False, verbose_name='Is Primary Contact?')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_closing_day_of_month', models.PositiveSmallIntegerField(default=22)),
                ('period_pay_day', models.PositiveSmallIntegerField(default=26)),
                ('declarations_type', models.CharField(max_length=128)),
                ('payslip_template', models.CharField(max_length=128)),
                ('payslip_printing_language', models.CharField(max_length=128)),
                ('salary_calculations_monthly', models.BooleanField(default=True)),
                ('salary_calculations_fornightly', models.BooleanField(default=False)),
                ('salary_calculations_weekly', models.BooleanField(default=False)),
                ('eoy_bonus', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False, verbose_name='Is Active?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=128, verbose_name='Short Name')),
                ('tan', models.CharField(max_length=32, verbose_name='TAN number')),
                ('npf', models.CharField(max_length=32, verbose_name='NPF number')),
                ('brn', models.CharField(max_length=32, verbose_name='Business Registration Number')),
                ('nature_of_business', models.CharField(max_length=32)),
                ('incorporation_date', models.TimeField(verbose_name='Incorporation Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyTimesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_time_input_from_employee', models.BooleanField(default=True)),
                ('automatic_lateness', models.BooleanField(default=True)),
                ('lateness_field', models.CharField(max_length=32)),
                ('lateness_calculation_type', models.CharField(max_length=32)),
                ('lateness_absence_field', models.CharField(max_length=32)),
                ('automatic_overtime', models.BooleanField(default=True)),
                ('overtime_field', models.CharField(max_length=32)),
                ('overtime_calculation_type', models.CharField(max_length=32)),
                ('overtime_calculation_option', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
