# Generated by Django 4.2.11 on 2024-04-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_companybank_companycontact_companypayrollsettings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyBank',
            new_name='CompanyBankAccount',
        ),
        migrations.CreateModel(
            name='PaymentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('formula', models.TextField()),
                ('order', models.IntegerField()),
                ('version', models.IntegerField(default=1)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.paymentelement', verbose_name='First Version of this Payment Element')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
