# Generated by Django 4.2.11 on 2024-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_paymentelement_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='incorporation_date',
            field=models.DateField(verbose_name='Incorporation Date'),
        ),
    ]
