# Generated by Django 4.2.11 on 2024-04-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_companysettings_incorporation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypayrollsettings',
            name='active',
        ),
    ]
