# Generated by Django 4.2.11 on 2024-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_remove_companypayrollsettings_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollgroup',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
