# Generated by Django 4.2.11 on 2024-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_payrollgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingcalendar',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
