# Generated by Django 4.2.11 on 2024-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypayrollsettings',
            name='salary_calculations_fornightly',
        ),
        migrations.RemoveField(
            model_name='companypayrollsettings',
            name='salary_calculations_monthly',
        ),
        migrations.RemoveField(
            model_name='companypayrollsettings',
            name='salary_calculations_weekly',
        ),
        migrations.AddField(
            model_name='companypayrollsettings',
            name='salary_calculations_period',
            field=models.CharField(default='monthly', max_length=30),
        ),
    ]
